packages:
  - 'packages/**'
  - 'apps/**'

catalogs:
  node:
    '@types/node': 22.11.0
    typescript: 5.0.4
  nest10:
    '@nestjs/cli': 10.4.8
    '@nestjs/common': 10.4.11
    '@nestjs/core': 10.4.11
    '@nestjs/microservices': 9.3.9
    '@nestjs/platform-fastify': 10.4.11
    '@nestjs/platform-express': 10.4.12
    'class-transformer': 0.5.1
    'class-validator': 0.14.1
    'reflect-metadata': 0.2.1
    'rxjs': 7.8.1
    '@nestjs/schematics': 10.2.3
    '@nestjs/testing': 10.4.11
    '@types/express': 4.17.21
